### ISSUE TITLE
Cyton Wallet's downloaded images can't display 

### ISSUE THREAD

**Issue by zengbing15** [citahub/citahub-docs#198] opened 2019-04-30 07:16 UTC
https://docs.citahub.com/en-US/toolchain/cyton/cyton-intro

![image](https://user-images.githubusercontent.com/40650475/56945737-b0dccd80-6b5a-11e9-948a-be215cd36ad8.png)

**Comment by wuyuyue** [comment] 2019-05-05 12:08
Duplicate of #206, but need smaller icon I think

**Closed as completed** 2019-05-10 03:00 UTC
Labels: bug
